"use client";

import { GetServerSideProps } from "next";
import SEO from "@/components/layout/SEO";
import Link from "next/link";
import { motion } from "framer-motion";
import { FiArrowLeft, FiSlash } from "react-icons/fi";
import {
    fetchUserProfile,
    fetchUserRepos,
    fetchUserEvents,
    fetchContributions,
    fetchPinnedRepos
} from "@/lib/github/queries";
import { calculateScorecard } from "@/lib/scoring/calculator";
import { DetailedScorecard } from "@/lib/github/types";
import dynamic from "next/dynamic";

const ComparisonView = dynamic(() => import("@/components/features/ComparisonView"), {
    loading: () => <div className="h-96 w-full animate-pulse bg-white/10 rounded-3xl" />,
    ssr: true
});

interface ComparePageProps {
    scorecard1: DetailedScorecard | null;
    scorecard2: DetailedScorecard | null;
    error?: string;
}

export default function ComparePage({ scorecard1, scorecard2, error }: ComparePageProps) {
    if (error || !scorecard1 || !scorecard2) {
        return (
            <div className="flex flex-col items-center justify-center min-h-[60vh] gap-6">
                <div className="p-8 rounded-3xl bg-red-400/5 border border-red-400/10 text-center">
                    <h2 className="text-xl font-bold text-red-100 mb-2">Clash Interrupted</h2>
                    <p className="text-red-400/60 text-sm max-w-sm">{error || "Failed to summon both explorers for comparison."}</p>
                </div>
                <Link href="/" className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-cyan-primary hover:text-white transition-colors">
                    <FiArrowLeft /> Back to Search
                </Link>
            </div>
        );
    }

    return (
        <>
            <SEO
                title={`${scorecard1.username} vs ${scorecard2.username} | GitScore Battle`}
                description={`A side-by-side GitHub engineering battle between ${scorecard1.username} and ${scorecard2.username}. See who reigns supreme in the mystical coordinates.`}
            />

            <div className="max-w-7xl mx-auto px-4 py-8 space-y-12">
                {/* Navigation */}
                <div className="flex items-center justify-between">
                    <Link href={`/score/${scorecard1.username}`} className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-foreground/40 hover:text-cyan-primary transition-colors">
                        <FiArrowLeft /> Back to {scorecard1.username}
                    </Link>
                    <div className="text-[10px] font-black uppercase tracking-[0.3em] text-cyan-primary/40">
                        Battle Log: CLSH-{(scorecard1.totalScore + scorecard2.totalScore).toString().padStart(3, '0')}{(scorecard1.username.length + scorecard2.username.length).toString().padStart(2, '0')}
                    </div>
                </div>

                {/* Intro Header */}
                <div className="text-center space-y-4">
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-primary/5 border border-cyan-primary/10 text-[10px] font-black uppercase tracking-[0.3em] text-cyan-primary mb-2"
                    >
                        <FiSlash className="rotate-45" /> The Ultimate Coordinate Clash
                    </motion.div>
                    <h1 className="text-4xl sm:text-6xl font-black text-white tracking-tighter">
                        Profile <span className="bg-clip-text text-transparent bg-gradient-to-r from-cyan-primary to-purple-500">Battle</span>
                    </h1>
                    <p className="text-sm text-foreground/40 font-bold uppercase tracking-widest">Two explorers. One mystical champion.</p>
                </div>

                {/* Main Comparison Component */}
                <ComparisonView scorecard1={scorecard1} scorecard2={scorecard2} />

                {/* Footer Credit */}
                <div className="text-center pt-24 pb-12 opacity-20">
                    <p className="text-[10px] font-black uppercase tracking-[0.5em] text-white">Generated by GitScore Battle Engine</p>
                </div>
            </div>
        </>
    );
}

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
    const { username1, username2 } = params as { username1: string; username2: string };

    const getScorecard = async (username: string): Promise<DetailedScorecard> => {
        const [user, repos, events, contrib, pinned] = await Promise.all([
            fetchUserProfile(username),
            fetchUserRepos(username),
            fetchUserEvents(username),
            fetchContributions(username),
            fetchPinnedRepos(username)
        ]);
        if (!user) throw new Error(`User ${username} not found`);
        return calculateScorecard({ user, repos, events, contrib, pinned });
    };

    try {
        const [scorecard1, scorecard2] = await Promise.all([
            getScorecard(username1),
            getScorecard(username2)
        ]);

        return {
            props: {
                scorecard1: JSON.parse(JSON.stringify(scorecard1)),
                scorecard2: JSON.parse(JSON.stringify(scorecard2)),
            }
        };
    } catch (err: any) {
        return {
            props: {
                scorecard1: null,
                scorecard2: null,
                error: err.message
            }
        };
    }
};
